const Appimages= {
    HomeTab: require('../assets/images/selected_home_btn.png'),
    HomeTab1: require('../assets/images/unselected_home_btn.png'),
    PunchTab: require('../assets/images/selected_punch_detail_btn.png'),
    PunchTab1: require('../assets/images/unselected_punch_detail_btn.png'),
    Drawer: require('../assets/images/side_menu_btn.png'),
    Profile: require('../assets/images/my_profile_icon.png'),
    Logout: require('../assets/images/logout_icon.png'),
    SideLogo: require('../assets/images/splash_screen_logo.png'),
    Notification: require('../assets/images/notification_icon.png'),
    About_us: require('../assets/images/about_us_icon.png'),
    News_events: require('../assets/images/news_blog_icon.png'),
    Apply_leave: require('../assets/images/selected_apply_leave_btn.png'),
    Apply_leave1: require('../assets/images/unselected_apply_leave_btn.png'),
    Leave_history: require('../assets/images/selected_leave_btn.png'),
    Leave_history1: require('../assets/images/unselected_leave_btn.png'),
    Log_out: require('../assets/images/logout_icon.png'),
    Poweredby_logo: require('../assets/images/powredby_redbytes.png'),
    Absent_icon:require('../assets/images/absent_status.png'),
    Holiday_icon:require('../assets/images/holiday_status.png'),
    Present_icon:require('../assets/images/present_status.png'),
    Time_punchout:require('../assets/images/time_punchout_circle_icon.png'),
    UpredArrow_icon:require('../assets/images/up_red.png'),
    DowngreenArrow_icon:require('../assets/images/down_green.png'),
    Futurepunchout_icon:require('../assets/images/future_punchout_circle.png'),
    Punchoutcircle_icon:require('../assets/images/punchout_circle_icon.png'),
    Dare_bubble_one:require('../assets/images/date_bubble_one.png'),
    Date_bubble_two:require('../assets/images/date_bubble_two.png'),
    Up_Arrow:require('../assets/images/up_arrow.png'),
    Back_Arrow:require('../assets/images/left_arrow_btn.png'),
    Profile1:require('../assets/images/me_profile.png'),
    Deductions:require('../assets/images/me_deductions.png'),
    Rewards:require('../assets/images/me_rewards.png'),
    Documents:require('../assets/images/me_documents.png'),
    punched_icon:require('../assets/images/punched_icon.png'),
    myProfile_icon:require('../assets/images/dummy_profile.png'),
    down_arrow:require('../assets/images/down_arrow.png'),
    Announcement:require('../assets/images/icons8-megaphone-48.png'),
    RaiseTicket:require('../assets/images/icons8-movie-ticket-48.png'),
    Time_circle:require('../assets/images/time_circle_icon.png'),
    Weekday_bg:require('../assets/images/week_day_bg.png'),
    Up_Arrow2:require('../assets/images/Up_arrow_2.png'),
    Select_Month:require('../assets/images/selected_month_rectangle.png'),
    Select_Day:require('../assets/images/selected_date_circle.png'),
    Select_toDay:require('../assets/images/present_day_circle.png'),


    
};

export default Appimages;